[phases.setup]
nixPkgs = ["nodejs_20", "yarn-1_x", "curl", "wget"]

[phases.build]
cmds = ["yarn build"]

[phases.start]
cmd = "yarn start"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--trace-warnings"